# @author SATO Kentaro
# @license BSD-2-Clause

name: Build and release

permissions:
  contents: write

on:
  push:
    branches: [master]
    tags: ['v[0-9]*']
    paths-ignore:
      - .*
      - '*[A-Z]'
      - '*.md'
      - '*.phpt'

jobs:
  build-ext:
    runs-on: windows-2022

    steps:
      - name: Archive
        id: archive
        shell: cmd
        run: |
          set arcName=arcnametest.zip
          echo lo_name=%arcName%>> %GITHUB_OUTPUT%
          echo UP_NAME=%arcName%>> %GITHUB_OUTPUT%
          echo co_name=%arcName%>> %GITHUB_OUTPUT%
          echo ::set-output name=ob_name::%arcName%
          echo %GITHUB_OUTPUT%
          type %GITHUB_OUTPUT%

      - name: Release
        shell: cmd
        run: |
          echo 
          echo lo_name=${{steps.archive.outputs.lo_name}}
          echo LO_NAME=${{steps.archive.outputs.LO_NAME}}
          
          echo up_name=${{steps.archive.outputs.up_name}}
          echo UP_NAME=${{steps.archive.outputs.UP_NAME}}
          
          echo ob_name=${{steps.archive.outputs.ob_name}}
          echo OB_NAME=${{steps.archive.outputs.OB_NAME}}
