# @author SATO Kentaro
# @license BSD-2-Clause

name: Build and release

permissions:
  contents: write

on:
  push:
    branches: [master]
    tags: ['v[0-9]*']
    paths-ignore:
      - .*
      - '*[A-Z]'
      - '*.md'
      - '*.phpt'

jobs:
  build-ext:
    runs-on: windows-2022

    steps:
      - name: Archive
        id: archive
        shell: cmd
        run: |
          set arcName=sandbox.zip
          echo file>README.md
          7z a ${{github.workspace}}\%arcName% README.md
          echo arc_name=%arcName%>> %GITHUB_OUTPUT%

      - name: pre
        id: pre
        shell: cmd
        run: |
          echo name=${{steps.archive.outputs.arc_name}}
          dir ${{steps.archive.outputs.arc_name}}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          #draft: true
          #prerelease: true
          files: ${{github.workspace}}\${{steps.archive.outputs.arc_name}}

      - name: post
        id: post
        shell: cmd
        run: |
          echo name=${{steps.archive.outputs.arc_name}}
          dir ${{steps.archive.outputs.arc_name}}
